apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-svc
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployement
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influx-img
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_USER
          value: "admin"
        - name: INFLUXDB_USER_PASSWORD
          value: "12345"
        - name: INFLUXDB_DB
          value: "main"
        ports:
        - containerPort: 8086
        volumeMounts:
        - name     : influxdb-volume
          mountPath: "/var/lib/influxdb"
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
