apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app  : mysql-svc
spec:
  type: ClusterIP
  ports:
  - name: port-mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployement
  labels:
    app  : mysql
spec:
  selector:
    matchLabels:
       app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : mysql
    spec:
      containers:
      - name           : mysql
        image          : mysql-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name     : mysql-volume
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
