apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv-min
      protocol: TCP
      port: 62000
      targetPort: 62000
    - name: pasv-mid
      protocol: TCP
      port: 62001
      targetPort: 62001
    - name: pasv-max
      protocol: TCP
      port: 62002
      targetPort: 62002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployement
  labels:
    app: ftps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 62000
          name: pasv-min
        - containerPort: 62001
          name: pasv-mid
        - containerPort: 62002
          name: pasv-max
